/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        rfBackground: "#f6f8fc",
        rfBackgroundDotted: "#f8fafc",
        rfSurface: "#ffffff",
        rfSurfaceSecondary: "#f9fafb",
        rfSurfaceTertiary: "#f1f5f9",
        rfSurfaceMuted: "#eef4ff",
        rfSurfaceBlue: "#eff6ff",
        rfBorder: "#e2e8f0",
        rfBorderLight: "#edf2f7",
        rfBorderMuted: "#cbd5e1",
        rfBorderStrong: "#94a3b8",
        rfTextPrimary: "#0f172a",
        rfTextSecondary: "#475569",
        rfTextMuted: "#94a3b8",
        rfTextSubtle: "#64748b",
        rfTextInverse: "#ffffff",
        rfPrimary: "#2563eb",
        rfPrimaryDark: "#1d4ed8",
        rfPrimaryDarker: "#1e40af",
        rfPrimaryLight: "#dbeafe",
        rfPrimaryLightest: "#eff6ff",
        rfPrimaryMuted: "#f0f7ff",
        rfSuccess: "#10b981",
        rfSuccessLight: "#d1fae5",
        rfSuccessLightest: "#ecfdf5",
        rfSuccessForeground: "#047857",
        rfWarning: "#f59e0b",
        rfWarningLight: "#fef3c7",
        rfWarningLightest: "#fffbeb",
        rfWarningForeground: "#92400e",
        rfError: "#ef4444",
        rfErrorLight: "#fee2e2",
        rfErrorLightest: "#fef2f2",
        rfErrorForeground: "#991b1b",
        rfNeutralLight: "#f1f5f9",
        rfNeutralForeground: "#334155",
      },
      borderRadius: {
        rfSm: 6,
        rfMd: 10,
        rfLg: 14,
        rfXl: 18,
        rf2xl: 24,
        rf3xl: 30,
      },
      fontFamily: {
        sans: ["Inter"],
      },
    },
  },
  plugins: [],
};
